name: periodical update README

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: '30 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
        # env:
        #   OPEN_WEATHER_MAP_KEY: ${{secrets.OPEN_WEATHER_MAP_KEY}}
      - name: Extract branch name  # cf. https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
        shell: bash
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: git setting
        run: git pull origin ${BRANCH_NAME}
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
